# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96f6eaf19fb71a4e129eaf5db31d1554f2b6827e9f3e1413c5ff761d0dda939d72e3bf8c8669dd16ffe131de3586b1468e3d9a853788b8bab19572a23a6cc1f3

test:
  secret_key_base: b427366b91d345461ad7a4b98788be83fd02b337fc945edbf0afb48ad34535576b087964cea69a4ae859a8b67b9a5ff747c08703efdb0954ab63686b66cc217c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
